version: 0.1

phases:
  install:
    commands:
      -
  pre_build:
    commands:
      # Run all tests included with our application
      - go test ./src/pkg1/bank_system_test.go

  build:
    commands:
      # Build our application
      - go build && ./src/pkg1/main

artifacts:
  files:
    -
